### ISSUE TITLE
Dynamic rendering for pinned repos

### ISSUE THREAD

**Issue by Mason-Austin** [nss-evening-cohort-E23/gitsub-the-commit-commandos#30]
Create the javascript to dynamically render pinned repos, and the ability to add new pinned repos through a form.

**Comment by DavidBPoole** [comment]
JS code written and tested along with Mason's fix for correctly running render to dom functions in the correct order depending on which page is currently loaded. Working as of 5/12 on branch "render-overview".

**Comment by DavidBPoole** [comment]
Renders completed with patch from Mason.
